// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    "intro",
    {
      type: "category",
      label: "Tutorial",
      items: [{ type: "autogenerated", dirName: "tutorial" }],
      collapsible: false,
      collapsed: false,
    },
    "api",
    {
      type: "category",
      label: "Packages",
      items: [{ type: "autogenerated", dirName: "canvas/packages" }],
      collapsible: false,
      collapsed: false,
    },
    "about",
  ],
}

module.exports = sidebars
